### ISSUE TITLE
dj-rest-auth installation failure

### ISSUE THREAD

**Issue by TareqMonwer** [iMerica/dj-rest-auth#245]
Hi!
I'm using python 3.9 with pyenv on my ubuntu 20.04 machine. I'm trying to install dj-rest-auth with pip and pipenv.
None of these seems working and they produces this error message:

`Collecting dj-rest-auth
  Using cached dj-rest-auth-2.1.4.tar.gz (92 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/tareq/.local/share/virtualenvs/drf-leadmanager-Y7gYN7kW/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-adkxfjll/dj-rest-auth/setup.py'"'"'; __file__='"'"'/tmp/pip-install-adkxfjll/dj-rest-auth/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-adkxfjll/dj-rest-auth/pip-egg-info
         cwd: /tmp/pip-install-adkxfjll/dj-rest-auth/
    Complete output (13 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/tareq/.local/share/virtualenvs/drf-leadmanager-Y7gYN7kW/lib/python3.9/site-packages/setuptools/__init__.py", line 20, in <module>
        from setuptools.dist import Distribution, Feature
      File "/home/tareq/.local/share/virtualenvs/drf-leadmanager-Y7gYN7kW/lib/python3.9/site-packages/_virtualenv.py", line 74, in exec_module
        old(module)
      File "/home/tareq/.local/share/virtualenvs/drf-leadmanager-Y7gYN7kW/lib/python3.9/site-packages/setuptools/dist.py", line 36, in <module>
        from setuptools import windows_support
      File "/home/tareq/.local/share/virtualenvs/drf-leadmanager-Y7gYN7kW/lib/python3.9/site-packages/setuptools/windows_support.py", line 2, in <module>
        import ctypes
      File "/home/tareq/.pyenv/versions/3.9.0/lib/python3.9/ctypes/__init__.py", line 8, in <module>
        from _ctypes import Union, Structure, Array
    ModuleNotFoundError: No module named '_ctypes'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`

Any clue how can I install this package?

It was working nicely with python 3.9 in my manjaro machine. Don't know what's wrong here, it might be pyenv or something else.

**Comment by iMerica** [comment]
The error you pasted is not related to this package. You might want to nuke your virtual environment and start from scratch.
