### ISSUE TITLE
django.urls.exceptions.NoReverseMatch: Reverse for 'socialaccount_signup' not found.

### ISSUE THREAD

**Issue by mahieyin-rahmun** [iMerica/dj-rest-auth#256]
### What is the issue?

I am trying to setup social authentication with `django-rest-framework` in the backend and Next.js + Next-Auth in the front end. So far, everything has worked alright except the following scenario:

- I have two providers currently, Google and Github.
- I can sign in using Google (let's say using an email xyz@gmail.com). No issues.
- I log out and sign in using Github (let's say using an email abc@gmail.com). No issues.
- I log out and sign using Google with abc@gmail.com, and then I get the error `django.urls.exceptions.NoReverseMatch: Reverse for 'socialaccount_signup' not found. 'socialaccount_signup' is not a valid view function or pattern name.`

### Relevant information

`requirements.txt`
```
dj-rest-auth==2.1.4
Django==3.2.2
django-allauth==0.44.0
django-cors-headers==3.7.0
djangorestframework==3.12.4
djangorestframework-simplejwt==4.6.0
```

`main/urls.py`
```
urlpatterns = [
    path('admin/', admin.site.urls),
    path("api/v1/auth/", include("dj_rest_auth.urls")),
    path("api/v1/auth/registration/", include('dj_rest_auth.registration.urls')),
    path("api/v1/auth/social/", include("authentication.urls")),
    url(r"^api/v1/media/(?P<path>.*)$", serve, { "document_root": settings.MEDIA_ROOT, }),
]
```

`authentication/urls.py`
```
urlpatterns = [
  path("google/", GoogleLoginView.as_view(), name = "google"),
  path("github/", GithubLoginView.as_view(), name = "github"),
]
```

`stacktrace`
```
Internal Server Error: /api/v1/social/login/google/
Traceback (most recent call last):
  File "/home/phantomhive/anaconda3/envs/careerhacks/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/phantomhive/anaconda3/envs/careerhacks/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/phantomhive/anaconda3/envs/careerhacks/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/phantomhive/anaconda3/envs/careerhacks/lib/python3.7/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/phantomhive/anaconda3/envs/careerhacks/lib/python3.7/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/phantomhive/anaconda3/envs/careerhacks/lib/python3.7/site-packages/django/views/decorators/debug.py", line 89, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/home/phantomhive/anaconda3/envs/careerhacks/lib/python3.7/site-packages/dj_rest_auth/views.py", line 48, in dispatch
    return super(LoginView, self).dispatch(*args, **kwargs)
  File "/home/phantomhive/anaconda3/envs/careerhacks/lib/python3.7/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/phantomhive/anaconda3/envs/careerhacks/lib/python3.7/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/phantomhive/anaconda3/envs/careerhacks/lib/python3.7/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/phantomhive/anaconda3/envs/careerhacks/lib/python3.7/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/phantomhive/anaconda3/envs/careerhacks/lib/python3.7/site-packages/dj_rest_auth/views.py", line 113, in post
    self.serializer.is_valid(raise_exception=True)
  File "/home/phantomhive/anaconda3/envs/careerhacks/lib/python3.7/site-packages/rest_framework/serializers.py", line 220, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/phantomhive/anaconda3/envs/careerhacks/lib/python3.7/site-packages/rest_framework/serializers.py", line 422, in run_validation
    value = self.validate(value)
  File "/home/phantomhive/anaconda3/envs/careerhacks/lib/python3.7/site-packages/dj_rest_auth/registration/serializers.py", line 135, in validate
    complete_social_login(request, login)
  File "/home/phantomhive/anaconda3/envs/careerhacks/lib/python3.7/site-packages/allauth/socialaccount/helpers.py", line 151, in complete_social_login
    return _complete_social_login(request, sociallogin)
  File "/home/phantomhive/anaconda3/envs/careerhacks/lib/python3.7/site-packages/allauth/socialaccount/helpers.py", line 172, in _complete_social_login
    ret = _process_signup(request, sociallogin)
  File "/home/phantomhive/anaconda3/envs/careerhacks/lib/python3.7/site-packages/allauth/socialaccount/helpers.py", line 22, in _process_signup
    url = reverse("socialaccount_signup")
  File "/home/phantomhive/anaconda3/envs/careerhacks/lib/python3.7/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/phantomhive/anaconda3/envs/careerhacks/lib/python3.7/site-packages/django/urls/resolvers.py", line 694, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'socialaccount_signup' not found. 'socialaccount_signup' is not a valid view function or pattern name.
```

### What is expected
Usually, when an account exists from a different provider but same email, I would like the user to see an error message that s/he should use the original account s/he used to sign in/up.

**Comment by mahieyin-rahmun** [comment]
This was fixed (at least for now) by adding the following line in `main/urls.py`

```
urlpatterns = [
    # ... other URLs
    url(r"^accounts", include("allauth.urls")),
     # ... other URLs
]
```

Although I am not exactly sure why this works or why it is not mentioned in the documentation.
