### ISSUE TITLE
Using with django-allauth and `is_active` is set to False, it tries to return `account_inactive`

### ISSUE THREAD

**Issue by taiki-okano** [iMerica/dj-rest-auth#264]
When django-allauth is installed, it tries to login with allauth, and if `is_active` of the user is set to False, allauth tries to return the `account_inactive` page which does not exist.

**Comment by taiki-okano** [comment]
You get something like below.
```
backend_1       | Internal Server Error: /api/Auth/SocialLogin/Google/
backend_1       | Traceback (most recent call last):
backend_1       |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
backend_1       |     response = get_response(request)
backend_1       |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
backend_1       |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
backend_1       |   File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
backend_1       |     return view_func(*args, **kwargs)
backend_1       |   File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
backend_1       |     return self.dispatch(request, *args, **kwargs)
backend_1       |   File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
backend_1       |     return bound_method(*args, **kwargs)
backend_1       |   File "/usr/local/lib/python3.9/site-packages/django/views/decorators/debug.py", line 89, in sensitive_post_parameters_wrapper
backend_1       |     return view(request, *args, **kwargs)
backend_1       |   File "/usr/local/lib/python3.9/site-packages/dj_rest_auth/views.py", line 54, in dispatch
backend_1       |     return super().dispatch(*args, **kwargs)
backend_1       |   File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
backend_1       |     response = self.handle_exception(exc)
backend_1       |   File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
backend_1       |     self.raise_uncaught_exception(exc)
backend_1       |   File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
backend_1       |     raise exc
backend_1       |   File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
backend_1       |     response = handler(request, *args, **kwargs)
backend_1       |   File "/usr/local/lib/python3.9/site-packages/dj_rest_auth/views.py", line 125, in post
backend_1       |     self.serializer.is_valid(raise_exception=True)
backend_1       |   File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 220, in is_valid
backend_1       |     self._validated_data = self.run_validation(self.initial_data)
backend_1       |   File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 422, in run_validation
backend_1       |     value = self.validate(value)
backend_1       |   File "/usr/local/lib/python3.9/site-packages/dj_rest_auth/registration/serializers.py", line 151, in validate
backend_1       |     complete_social_login(request, login)
backend_1       |   File "/usr/local/lib/python3.9/site-packages/allauth/socialaccount/helpers.py", line 151, in complete_social_login
backend_1       |     return _complete_social_login(request, sociallogin)
backend_1       |   File "/usr/local/lib/python3.9/site-packages/allauth/socialaccount/helpers.py", line 166, in _complete_social_login
backend_1       |     ret = _login_social_account(request, sociallogin)
backend_1       |   File "/usr/local/lib/python3.9/site-packages/allauth/socialaccount/helpers.py", line 48, in _login_social_account
backend_1       |     return perform_login(
backend_1       |   File "/usr/local/lib/python3.9/site-packages/allauth/account/utils.py", line 165, in perform_login
backend_1       |     return adapter.respond_user_inactive(request, user)
backend_1       |   File "/usr/local/lib/python3.9/site-packages/allauth/account/adapter.py", line 467, in respond_user_inactive
backend_1       |     return HttpResponseRedirect(reverse("account_inactive"))
backend_1       |   File "/usr/local/lib/python3.9/site-packages/django/urls/base.py", line 86, in reverse
backend_1       |     return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
backend_1       |   File "/usr/local/lib/python3.9/site-packages/django/urls/resolvers.py", line 694, in _reverse_with_prefix
backend_1       |     raise NoReverseMatch(msg)
backend_1       | django.urls.exceptions.NoReverseMatch: Reverse for 'account_inactive' not found. 'account_inactive' is not a valid view function or pattern name.

```
