### ISSUE TITLE
NameError: name 'get_adapter' is not defined

### ISSUE THREAD

**Issue by gamino97** [iMerica/dj-rest-auth#306]
Hi, I'm not using allauth library in my project, and when I want to reset the password using the url '/dj-rest-auth/password/reset/' I get that error:

Log trace:
`Traceback (most recent call last):
  File "/home/gamino/.virtualenvs/restaurante/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/gamino/.virtualenvs/restaurante/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gamino/.virtualenvs/restaurante/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/gamino/.virtualenvs/restaurante/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/gamino/.virtualenvs/restaurante/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/gamino/.virtualenvs/restaurante/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/gamino/.virtualenvs/restaurante/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/gamino/.virtualenvs/restaurante/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/gamino/.virtualenvs/restaurante/lib/python3.9/site-packages/dj_rest_auth/views.py", line 248, in post
    serializer.is_valid(raise_exception=True)
  File "/home/gamino/.virtualenvs/restaurante/lib/python3.9/site-packages/rest_framework/serializers.py", line 220, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/gamino/.virtualenvs/restaurante/lib/python3.9/site-packages/rest_framework/serializers.py", line 419, in run_validation
    value = self.to_internal_value(data)
  File "/home/gamino/.virtualenvs/restaurante/lib/python3.9/site-packages/rest_framework/serializers.py", line 478, in to_internal_value
    validated_value = validate_method(validated_value)
  File "/home/gamino/.virtualenvs/restaurante/lib/python3.9/site-packages/dj_rest_auth/serializers.py", line 243, in validate_email
    if not self.reset_form.is_valid():
  File "/home/gamino/.virtualenvs/restaurante/lib/python3.9/site-packages/django/forms/forms.py", line 175, in is_valid
    return self.is_bound and not self.errors
  File "/home/gamino/.virtualenvs/restaurante/lib/python3.9/site-packages/django/forms/forms.py", line 170, in errors
    self.full_clean()
  File "/home/gamino/.virtualenvs/restaurante/lib/python3.9/site-packages/django/forms/forms.py", line 372, in full_clean
    self._clean_fields()
  File "/home/gamino/.virtualenvs/restaurante/lib/python3.9/site-packages/django/forms/forms.py", line 393, in _clean_fields
    value = getattr(self, 'clean_%s' % name)()
  File "/home/gamino/.virtualenvs/restaurante/lib/python3.9/site-packages/dj_rest_auth/forms.py", line 27, in clean_email
    email = get_adapter().clean_email(email)
NameError: name 'get_adapter' is not defined
`

I think the error is in this piece of code:
`
from django.conf import settings
from django.contrib.sites.shortcuts import get_current_site
from django.urls import reverse

if 'allauth' in settings.INSTALLED_APPS:
    from allauth.account import app_settings
    from allauth.account.adapter import get_adapter
    from allauth.account.forms import \
        ResetPasswordForm as DefaultPasswordResetForm
    from allauth.account.forms import default_token_generator
    from allauth.account.utils import (filter_users_by_email,
                                       user_pk_to_url_str, user_username)
    from allauth.utils import build_absolute_uri
else:
    from django.contrib.auth.forms import PasswordResetForm as DefaultPasswordResetForm
    from django.contrib.auth.tokens import default_token_generator

class PasswordResetForm(DefaultPasswordResetForm):
    def clean_email(self):
        """
        Invalid email should not raise error, as this would leak users
        for unit test: test_password_reset_with_invalid_email
        """
        email = self.cleaned_data["email"]
        email = get_adapter().clean_email(email)
        self.users = filter_users_by_email(email, is_active=True)
        return self.cleaned_data["email"]
`
As I don't have 'allauth' in INSTALLED_APPS, the get_adapter function is not working, but I don't need allauth because I'm doing my own registration code, forgive my bad english.

**Comment by gamino97** [comment]
I think that also will give an error with ```filter_users_by_email``` in line 28.
