### ISSUE TITLE
Github signup shows {"non_field_errors": [ "Incorrect value"  ]}

### ISSUE THREAD

**Issue by Mahadi-Ahammed** [iMerica/dj-rest-auth#426]
Hi, I was trying to create a api for sign up using github account but when i submit the "code" or "access_token" using post method to the "GitHubLogin" view it shows:

HTTP 400 Bad Request
Allow: POST, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "non_field_errors": [
        "Incorrect value"
    ]
}

I have added the client id and secret in db, Social Application. Also I have seen other related issues but couldn't find the solution.

**Comment by Mahadi-Ahammed** [comment]
Here is the log if i submit the 'Code' 

`Environment:


Request Method: POST
Request URL: http://127.0.0.1:8000/api/accounts/dj-rest-auth/github/?code=6dfda01f968c02314485

Django Version: 4.0.6
Python Version: 3.9.13
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'accounts',
 'rest_framework',
 'rest_framework_simplejwt.token_blacklist',
 'rest_framework.authtoken',
 'dj_rest_auth',
 'django.contrib.sites',
 'allauth',
 'allauth.account',
 'dj_rest_auth.registration',
 'allauth.socialaccount',
 'allauth.socialaccount.providers.google',
 'allauth.socialaccount.providers.github']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "G:\ProjectCodes\wishgrad\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "G:\ProjectCodes\wishgrad\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\ProjectCodes\wishgrad\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "G:\ProjectCodes\wishgrad\env\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "G:\ProjectCodes\wishgrad\env\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "G:\ProjectCodes\wishgrad\env\lib\site-packages\django\views\decorators\debug.py", line 92, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "G:\ProjectCodes\wishgrad\env\lib\site-packages\dj_rest_auth\views.py", line 53, in dispatch
    return super().dispatch(*args, **kwargs)
  File "G:\ProjectCodes\wishgrad\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "G:\ProjectCodes\wishgrad\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "G:\ProjectCodes\wishgrad\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "G:\ProjectCodes\wishgrad\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "G:\ProjectCodes\wishgrad\env\lib\site-packages\dj_rest_auth\views.py", line 130, in post
    self.serializer.is_valid(raise_exception=True)
  File "G:\ProjectCodes\wishgrad\env\lib\site-packages\rest_framework\serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "G:\ProjectCodes\wishgrad\env\lib\site-packages\rest_framework\serializers.py", line 429, in run_validation
    value = self.validate(value)
  File "G:\ProjectCodes\wishgrad\env\lib\site-packages\dj_rest_auth\registration\serializers.py", line 133, in validate
    token = client.get_access_token(code)
  File "G:\ProjectCodes\wishgrad\env\lib\site-packages\allauth\socialaccount\providers\oauth2\client.py", line 91, in get_access_token
    raise OAuth2Error("Error retrieving access token: %s" % resp.content)

Exception Type: OAuth2Error at /api/accounts/dj-rest-auth/github/
Exception Value: Error retrieving access token: b'error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch2'
`

**Comment by arthtyagi** [comment]
Are you sure that you have the correct URI in your app on Github? It says right there in your error if you look closely.

`error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch2'`

**Comment by Mahadi-Ahammed** [comment]
@arthtyagi Thanks for the reply.
I am able to receive the **'code'** using the same **redirect_uri** but if I submit the code using post method to the **"GitHubLogin" view** then it **unable to retrieve the access_token** and shows that error.
