### ISSUE TITLE
Password reset error

### ISSUE THREAD

**Issue by Naitik4516** [iMerica/dj-rest-auth#596]
```
Internal Server Error: /auth/password/reset/
Traceback (most recent call last):
  File "E:\Programming\Big projects\Techno Master\backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Programming\Big projects\Techno Master\backend\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Programming\Big projects\Techno Master\backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Programming\Big projects\Techno Master\backend\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Programming\Big projects\Techno Master\backend\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Programming\Big projects\Techno Master\backend\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Programming\Big projects\Techno Master\backend\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\Programming\Big projects\Techno Master\backend\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Programming\Big projects\Techno Master\backend\venv\Lib\site-packages\dj_rest_auth\views.py", line 250, in post
    serializer.save()
  File "E:\Programming\Big projects\Techno Master\backend\venv\Lib\site-packages\dj_rest_auth\serializers.py", line 254, 
in save
    self.reset_form.save(**opts)
  File "E:\Programming\Big projects\Techno Master\backend\venv\Lib\site-packages\dj_rest_auth\forms.py", line 64, in save    url = url_generator(request, user, temp_key)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Programming\Big projects\Techno Master\backend\venv\Lib\site-packages\dj_rest_auth\forms.py", line 23, in default_url_generator
    path = reverse(
           ^^^^^^^^
  File "E:\Programming\Big projects\Techno Master\backend\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Programming\Big projects\Techno Master\backend\venv\Lib\site-packages\django\urls\resolvers.py", line 851, in 
_reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'password_reset_confirm' not found. 'password_reset_confirm' is not a 
valid view function or pattern name.
```

I think there is a typo error in either **dj_rest_auth/views.py _line 30:63_** name or **dj_rest_auth/forms.py line _34:9_** in _default_url_generator_ 's _reverse_ function's viewname. Because it is **rest_password_reset** in views and **password_reset_confirm** in forms.

 **dj_rest_auth version: 5.0.2**

**Comment by flange-ipb** [comment]
Hi @Naitik4516 
This is expected behaviour. See [FAQ item 2](https://dj-rest-auth.readthedocs.io/en/stable/faq.html) and [demo/demo/urls.py](https://github.com/iMerica/dj-rest-auth/blob/master/demo/demo/urls.py#L44).
